### ISSUE TITLE
Using @doc and doctests for API

### ISSUE THREAD

**Issue by h4cc** [SRVentures/caramelize#2]
Currently no `@doc` is used in the public function `Caramelize.camelize`. These are quite handy for docs and examples.

Example:

```elixir
@doc """
Camelizing a given structure.

  iex> Caramelize.camelize "a_b"
  aB
"""
def camelize(key) when is_atom(key) do
  key |> Atom.to_string |> camelize
end
```

More on that topic:
http://elixir-lang.org/docs/stable/ex_unit/ExUnit.DocTest.html

**Comment by sgtpepper43** [comment]
Resolved by #3
